const express = require("express")
const cors = require("cors")
const sqlite3 = require("sqlite3").verbose()
const app = express()
app.use(cors())
app.use(express.json())
const db = new sqlite3.Database("./players.db")